services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USERNAME=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - '5432:5432'

  products:
    build: .
    image: robertst98/products
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_started
