apiVersion: v1
kind: Service
metadata:
  name: primary-db-service
  labels:
    service: postgres-primary
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    service: postgres-primary
---
apiVersion: v1
kind: Service
metadata:
  name: replica-db-service
  labels:
    service: postgres-replica
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    service: postgres-replica
