apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: products
  name: products
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: products
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: products
    spec:
      containers:
        - env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database-name
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database-environment
          image: robertst98/products
          name: products
          ports:
            - containerPort: 3000
              protocol: TCP
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: io.kompose.service
                    operator: In
                    values:
                      - products
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always
