apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: products
  name: products
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
      targetPort: 3000
  selector:
    io.kompose.service: products
